CREATE TABLE HABITACIONES
(
    ID           VARCHAR(9),
    ID_HOTEL     VARCHAR(9),
    NUMERO       VARCHAR(10),
    TIPO         VARCHAR(50),
    PRECIO       NUMERIC(10, 2),
    DISPONIBLE   BOOLEAN,

    CONSTRAINT "PK_HABITACIONES"              PRIMARY KEY (ID),
    CONSTRAINT "FK_HABITACIONES_HOTELES"      FOREIGN KEY (ID_HOTEL) REFERENCES HOTELES(ID),
    CONSTRAINT "NN_HABITACIONES.ID_HOTEL"     CHECK (ID_HOTEL IS NOT NULL),
    CONSTRAINT "NN_HABITACIONES.NUMERO"       CHECK (NUMERO IS NOT NULL),
    CONSTRAINT "NN_HABITACIONES.TIPO"         CHECK (TIPO IS NOT NULL),
    CONSTRAINT "NN_HABITACIONES.PRECIO"       CHECK (PRECIO IS NOT NULL),
    CONSTRAINT "CH_HABITACIONES.PRECIO"       CHECK (PRECIO > 0)
);