CREATE TABLE CLIENTES
(
    ID          VARCHAR(9),
    NOMBRE      VARCHAR(100),
    EMAIL       VARCHAR(100),
    TELEFONO    VARCHAR(15),

    CONSTRAINT "PK_CLIENTES"               PRIMARY KEY (ID),
    CONSTRAINT "NN_CLIENTES.NOMBRE"        CHECK (NOMBRE IS NOT NULL),
    CONSTRAINT "NN_CLIENTES.EMAIL"         CHECK (EMAIL IS NOT NULL),
    CONSTRAINT "NN_CLIENTES.TELEFONO"      CHECK (TELEFONO IS NOT NULL)
);