CREATE TABLE HOTELES
(
    ID            VARCHAR(9),
    NOMBRE        VARCHAR(100),
    CIUDAD        VARCHAR(50),
    ESTRELLAS     NUMERIC(1),
    DESCRIPCION   VARCHAR(400),

    CONSTRAINT "PK_HOTELES"                PRIMARY KEY (ID),
    CONSTRAINT "NN_HOTELES.NOMBRE"         CHECK (NOMBRE IS NOT NULL),
    CONSTRAINT "NN_HOTELES.CIUDAD"         CHECK (CIUDAD IS NOT NULL),
    CONSTRAINT "NN_HOTELES.ESTRELLAS"      CHECK (ESTRELLAS IS NOT NULL),
    CONSTRAINT "CH_HOTELES.ESTRELLAS"      CHECK (ESTRELLAS BETWEEN 1 AND 5)
);