CREATE TABLE RESERVAS
(
    ID             VARCHAR(9),
    ID_CLIENTE     VARCHAR(9),
    ID_HABITACION  VARCHAR(9),
    FECHA_ENTRADA  DATE,
    FECHA_SALIDA   DATE,

    CONSTRAINT "PK_RESERVAS"                 PRIMARY KEY (ID),
    CONSTRAINT "FK_RESERVAS_CLIENTES"        FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTES(ID),
    CONSTRAINT "FK_RESERVAS_HABITACIONES"    FOREIGN KEY (ID_HABITACION) REFERENCES HABITACIONES(ID),
    CONSTRAINT "NN_RESERVAS.ID_CLIENTE"      CHECK (ID_CLIENTE IS NOT NULL),
    CONSTRAINT "NN_RESERVAS.ID_HABITACION"   CHECK (ID_HABITACION IS NOT NULL),
    CONSTRAINT "NN_RESERVAS.FECHA_ENTRADA"   CHECK (FECHA_ENTRADA IS NOT NULL),
    CONSTRAINT "NN_RESERVAS.FECHA_SALIDA"    CHECK (FECHA_SALIDA IS NOT NULL),
    CONSTRAINT "CH_RESERVAS.FECHA"           CHECK (FECHA_SALIDA > FECHA_ENTRADA)
);